### ISSUE TITLE
Add synthetic control as analysis method

### ISSUE THREAD

**Issue by david26694** [david26694/cluster-experiments#144]
Add a wrapper to a synthetic control implementation that gives p-values, this should allow us to treat synthetic control as just another analysis method and check if it has higher power than simpler things

**Comment by Gabrielcidral1** [comment]
Yes I think we can use our own implementation. 

Just the calculation of p-values that could be a bit tricky as it requires parallel processing to speed up calculation

**Comment by david26694** [comment]
> For me it's a bit confusing what types of splitters are allowed using this method. For example, do we allow Switchback experiments?

I wouldn't, I'd just make it compatible with ClusteredSplitter and that's it. wdyt?

**Comment by Gabrielcidral1** [comment]
Make sense. Just to confirm we're in the same page: In a case of synthetic control, normally the data it's observational, so we know the treatment and control groups. However, in this case we will leave the assignment random because we want to test the method of analysis of synthetic controls. This means that for each treatment unit, we will use the control units to build a weighted average.

The main peculiarity of this type of analysis is the requirement of a time feature.  

To calculate p-values we could use the Fisher Permutation test, where we count the times the real treatment city has higher effect than using another control city as placebo treatment.
